<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Phase 12 — live classes via Jitsi Meet.
 *
 * jitsi_room_name is generated by the LiveClass model on creating (32 random
 * letters + a dash + an 8-character [a-f] suffix derived from the tenant id —
 * digit-free by design, so no numeric id can ever appear inside a room name)
 * and is never accepted from a client: the unique (tenant_id, jitsi_room_name)
 * key makes a collision or a forced duplicate loud, and the room never leaves
 * the server as anything but a server-minted redirect URL.
 *
 * Both lesson_id and created_by are nullable by design (docs/specs/
 * phase-12-live-classes.md): a class is a course-level event that may or may
 * not hang off one lesson, and a class row must stay insertable even when its
 * creator record is unresolvable — mirroring courses.created_by.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('live_classes', function (Blueprint $table) {
            $table->id();
            $table->foreignId('tenant_id');
            $table->foreignId('course_id');
            $table->foreignId('lesson_id')->nullable();
            $table->foreignId('created_by')->nullable();
            $table->string('title', 150);
            $table->text('description')->nullable();
            $table->dateTime('starts_at');
            $table->dateTime('ends_at')->nullable();
            $table->string('status', 20)->default('scheduled');
            $table->string('jitsi_room_name', 64);
            $table->timestamps();

            $table->tenantKeys();
            $table->unique(['tenant_id', 'jitsi_room_name']);
            $table->index(['tenant_id', 'course_id', 'starts_at']);
            $table->index(['tenant_id', 'status', 'starts_at']);

            $table->tenantForeign('course_id', 'courses');
            $table->tenantForeign('created_by', 'users');

            // Restrict via the same macro (MySQL errno 150 correction): ON DELETE
            // SET NULL would need tenant_id itself to be nullable, which it never
            // is — every composite FK in this schema carries a non-null tenant_id.
            // So a lesson with a linked live class must be unlinked first, exactly
            // like courses and creators: no silent deletion of a session record.
            $table->tenantForeign('lesson_id', 'lessons');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('live_classes');
    }
};
